# Generated by Django 3.2.4 on 2021-06-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date_added',
            field=models.DateTimeField(editable=False),
        ),
    ]
